function Flash(){};Flash.Notes={};Flash.Notes.Keyboard={};Flash.Notes.Keyboard.Config=function(){this.TREBLE=0;this.BASS=1;this.ALTO=2;this.TENOR=3;this.TREBLE_OFFSET=10;this.BASS_OFFSET=12;this.ALTO_OFFSET=11;this.TENOR_OFFSET=9;this.PRACTICE_MODE=0;this.GAME_MODE=1;this.MAX_LEVEL=30;this.TIER_1=4;this.TIER_2=14;this.TIER_3=18;this.TIER_4=28;this.MIN_ATTEMPTS=5;this.MIN_PERCENT=80;this.TIMEOUT=12;this.BONUS_INC=this.BONUS=50;this.BONUS_LEVEL=12;this.MAX_LIVES=5;this.RANDOM_TB=4;this.RANDOM_AT=5;this.RANDOM_ALL=6;this.TOGGLE_OFF=0;this.TOGGLE_ON=1;this.TOGGLE_NONE=
-1;this.MIN_RANGE=0;this.MAX_RANGE=3;this.P_HIGH_PCT=70;this.P_LOW_PCT=60;this.PRACTICE_ATT=5;this.ENTER_KEY=13;this.ESC_KEY=27;this.UP_KEY=38;this.DOWN_KEY=40;this.KEY_C=65;this.KEY_CS=87;this.KEY_D=83;this.KEY_DS=69;this.KEY_E=68;this.KEY_F=70;this.KEY_FS=84;this.KEY_G=71;this.KEY_GS=89;this.KEY_A=72;this.KEY_AS=85;this.KEY_B=74;this.KEY_C2=75;this.SMALL="small";this.SMALL_W="small_w";this.NORMAL="normal";this.NORMAL_W="normal_w";this.MEDIUM="medium";this.MEDIUM_W="medium_w";this.LARGE="large";
this.LARGE_W="large_w";this.HUGE="huge";this.HUGE_W="huge_w";this.BG_STAVE_LEFT=20;this.BG_STAVE_TOP=10;this.BG_STAVE_WIDTH=100;this.BG_LAYER_WIDTH=320;this.BG_LAYER_HEIGHT=200;this.FG_STAVE_TOP=10;this.NOTE_LAYER_LEFT=this.KS_LAYER_LEFT=this.CLEF_LAYER_LEFT=0;this.CLEF_LAYER_WIDTH=70;this.KS_LAYER_WIDTH=100;this.NOTE_LAYER_WIDTH=146;this.CLEF_TYPES=["treble","bass","alto","tenor"];this.MIN_RANGE_INDEX=0;this.MAX_RANGE_INDEX=3;this.ACC_LEVELS=[5,6,19,20];this.KS_TIER_1=[7,14];this.KS_TIER_2=[21,30];
this.KS_EASY_LEVELS=[7,8,11,12,21,22,25,26,29];this.KS_HARD_LEVELS=[9,10,13,14,23,24,27,28,30];this.EASY_KEYS=0;this.HARD_KEYS=1;this.ACC_SINGLE=0;this.ACC_DOUBLE=1;this.ACC_ALL=2;this.ACC_SINGLE_NOT_C=3;this.ACC_ALL_NOT_C=4;this.ACC_NONE=-1;this.ACC_TYPE_C=0;this.ACC_TYPE_FLAT=-1;this.ACC_TYPE_SHARP=1;this.ACCIDENTAL_ON={single_acc:!1,double_acc:!1};this.C=7;this.CS=14;this.CF=0;this.D=9;this.DF=2;this.E=11;this.EF=4;this.F=6;this.FS=13;this.G=8;this.GF=1;this.A=10;this.AF=3;this.B=12;this.BF=5;
this.KEY_SIGS="Cb,Gb,Db,Ab,Eb,Bb,F,C,G,D,A,E,B,F#,C#".split(",");this.KS_C_INDEX=7;this.KS_EASY=[this.C,this.G,this.F,this.D,this.BF,this.A,this.EF];this.KS_HARD=[this.E,this.AF,this.B,this.DF,this.FS,this.GF,this.CS,this.CF];this.KS_SEL_WIDTH=55;this.KS_SEL_HEIGHT=45};Flash.Notes.Keyboard.noteRangeProperties=function(a){return Flash.Notes.Keyboard.noteRangeProperties.table[a]};
Flash.Notes.Keyboard.noteRangeProperties.table={0:{base_index:[1,6,4,2],base_octave:[4,3,3,4],upper_index:[4,6,1,3],upper_octave:[5,5,6,6]},1:{base_index:[3,1,6,4],base_octave:[2,2,1,1],upper_index:[6,1,3,5],upper_octave:[3,4,4,4]},2:{base_index:[2,0,5,3],base_octave:[3,3,2,2],upper_index:[5,0,2,4],upper_octave:[4,5,5,5]},3:{base_index:[0,5,3,1],base_octave:[3,2,2,2],upper_index:[3,5,0,2],upper_octave:[4,4,5,5]}};Flash.Notes.Keyboard.keyIdToElementId=function(a){return Flash.Notes.Keyboard.keyIdToElementId.table[a]};
Flash.Notes.Keyboard.keyIdToElementId.table={a:"c",w:"cs",s:"d",e:"ds",d:"e",f:"f",t:"fs",g:"g",y:"gs",h:"a",u:"as",j:"b",k:"c"};Flash.Notes.Keyboard.keySignatureAccidentals=function(a,b){a===void 0&&(a="C");return Flash.Notes.Keyboard.keySignatureAccidentals.table[a][b]};
Flash.Notes.Keyboard.keySignatureAccidentals.table={C:",,,,,,".split(","),"C#":"#,#,#,#,#,#,#".split(","),Cb:"b,b,b,b,b,b,b".split(","),D:"#,,,#,,,".split(","),Db:",b,b,,b,b,b".split(","),E:"#,#,,#,#,,".split(","),Eb:",,b,,,b,b".split(","),F:",,,,,,b".split(","),"F#":"#,#,#,#,#,#,".split(","),G:",,,#,,,".split(","),Gb:"b,b,b,,b,b,b".split(","),A:"#,,,#,#,,".split(","),Ab:",b,b,,,b,b".split(","),B:"#,#,,#,#,#,".split(","),Bb:",,b,,,,b".split(",")};function Merge(a,b){for(var c in b)a[c]=b[c];return a}function randomPos(a){return Math.floor(Math.random()*a)}function saveData(a,b){Modernizr.localstorage&&localStorage.setItem(a,b)}function getData(a){if(Modernizr.localstorage)return localStorage.getItem(a)};Flash.Notes.Keyboard.AjaxUtilities=function(){var a,b,c=!1;this.createXHR=function(){a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP")};this.getXHR=function(){return a};this.open=function(b,f){try{a.open(b,f,!0)}catch(e){c=!1}};this.send=function(b,f){try{a.setRequestHeader("Content-type","application/x-www-form-urlencoded"),a.send(f)}catch(e){c=!1}};this.onChange=function(){var d,f,e;if(a.readyState===4){if(a.status===200||a.statusText==="OK"){c=!0;try{b=a.responseXML;
f=b.getElementsByTagName("score");e=b.getElementsByTagName("time");ds=b.getElementsByTagName("date_string");ts=b.getElementsByTagName("time_string");for(d=0;d<f.length;d++)statusModel.top_scores[d]=f[d].childNodes[0].nodeValue,statusModel.top_times[d]=e[d].childNodes[0].nodeValue,statusModel.top_date_strings[d]=ds[d].childNodes[0].nodeValue,statusModel.top_time_strings[d]=ts[d].childNodes[0].nodeValue}catch(g){c=!1}}else c=!1;gameController.displayFinalScore(c);$("#main_menu_button").show()}}};Flash.Notes.Keyboard.GameController=function(){var a=!1;this.getMaxLevel=function(){return a};this.setMaxLevel=function(b){a=b};this.init()};
Flash.Notes.Keyboard.GameController.prototype.init=function(){statusModel.start(!1);statusModel.setTimeout(!1);statusModel.setTimeInterval(cfg.TIMEOUT);statusModel.setLevel(1);statusModel.setPoints(0);statusModel.setAttempts(0);statusModel.setScore(0);statusModel.setLives(cfg.MAX_LIVES);statusModel.setOverlayVisible(!1);statusView.displayKeyOverlay(!1);statusView.displayTime("#status_timer",0);notationController.hideNote();notationController.drawClef(cfg.TREBLE);notationModel.setKsIndex(cfg.KS_C_INDEX);
notationModel.setAddAccidental(!1);notationModel.setAccidentalRange(cfg.ACC_NONE);notationModel.setKeySignature(cfg.C);notationController.drawKeySignature(cfg.C);notationController.setRangeIndex(cfg.MIN_RANGE_INDEX);$("#start_button").hide();$("#stop_button").hide();this.initClefs(cfg.TREBLE);this.initAccidentals();this.displayScore();return this};Flash.Notes.Keyboard.GameController.prototype.setMode=function(a){statusModel.setMode(a)};
Flash.Notes.Keyboard.GameController.prototype.initClefs=function(a){var b;for(b=0;b<4;b++)statusModel.active_clefs[b]=!1,statusModel.clefButtons[b].removeClass("on"),statusModel.clefButtons[b].addClass("off");statusModel.active_clefs[a]=!0;statusModel.clefButtons[a].removeClass("off");statusModel.clefButtons[a].addClass("on")};
Flash.Notes.Keyboard.GameController.prototype.initAccidentals=function(){statusModel.accidental_on=!1;$("#acc_single_sel_button").removeClass("on");$("#acc_single_sel_button").addClass("off");$("#acc_double_sel_button").removeClass("on");$("#acc_double_sel_button").addClass("off");cfg.ACCIDENTAL_ON.single_acc=!1;cfg.ACCIDENTAL_ON.double_acc=!1};
Flash.Notes.Keyboard.GameController.prototype.startGame=function(a){var b=statusModel.getStart(),c=statusModel.getMode();statusModel.keyId="c";if(b)this.stopGame();else{statusModel.start(!0);document.getElementById("c").focus();switch(c){case cfg.GAME_MODE:this.startTimer(a,statusModel.getTimeInterval(),c);break;case cfg.PRACTICE_MODE:this.startTimer(a,0,c)}notationController.drawNote()}};
Flash.Notes.Keyboard.GameController.prototype.startTimer=function(a,b,c){var d,f=this;b<0?(clearTimeout(this.getT),statusModel.setTimeout(!0),this.stopGame()):d=setTimeout(function(){f.updateTimer(a,b,c,d)},1E3);statusView.displayTime(a,b);return this};
Flash.Notes.Keyboard.GameController.prototype.updateTimer=function(a,b,c,d){statusModel.getStart()&&c===cfg.GAME_MODE?(b-=1,statusModel.setTime(b),statusModel.setTimeInterval(b),this.startTimer(a,b,c,d)):statusModel.getStart()&&c===cfg.PRACTICE_MODE&&(b+=1,statusModel.setTime(b),this.startTimer(a,b,c,d))};
Flash.Notes.Keyboard.GameController.prototype.continueGame=function(a,b){var c,d=statusModel.getStart(),f=statusModel.getLevel(),e=statusModel.getMode()===cfg.GAME_MODE?!0:!1;statusModel.keyCode=parseInt(a)%12;statusModel.value=notationController.getNoteValue();(c=statusModel.keyCode===statusModel.value?!0:!1)?statusView.updateHitDisplay(!0):statusView.updateHitDisplay(!1);e&&!c&&(statusModel.decLives(),statusModel.getLives(),statusView.updateLivesDisplay());d&&c&&(this.getMaxLevel()?notationController.drawClef(notationController.getRandomClefIndex(4,
0)):(f>=5&&f<=8&&notationController.drawClef(notationController.getRandomClefIndex(2,0)),f>=13&&f<=16&&notationController.drawClef(notationController.getRandomClefIndex(2,2))),e||(this.setPracticeRange(),notationController.drawClef(statusModel.getRandomClefIndex())),notationController.drawNote(),statusModel.addPoint(),statusModel.calculateScore());d&&(statusModel.addAttempt(),this.displayScore(),document.getElementById(Flash.Notes.Keyboard.keyIdToElementId(b)).focus())};
Flash.Notes.Keyboard.GameController.prototype.stopGame=function(){var a,b;statusModel.start(!1);notationController.hideNote();document.getElementById(statusModel.keyId).blur();statusModel.getMode()===cfg.GAME_MODE?(a=statusModel.isLevelAdvance(),b=statusModel.getLives()>0?!1:!0,a&&(statusModel.advanceLevel(),statusModel.addBonus()),this.displaySessionAlert(!1,b,a)):(notationController.setRangeIndex(cfg.MIN_RANGE),$("#stop_button").hide(),$("#start_button").show(),this.displaySummary());return this};
Flash.Notes.Keyboard.GameController.prototype.resetGame=function(){statusModel.setTimeout(!1);statusModel.setTimeInterval(cfg.TIMEOUT);statusModel.setPoints(0);statusModel.setAttempts(0);this.displayScore()};Flash.Notes.Keyboard.GameController.prototype.getStart=function(){return statusModel.getStart()};
Flash.Notes.Keyboard.GameController.prototype.toggleClef=function(a){if(!statusModel.getStart()){var b=statusModel.toggleClefButton(a);notationModel.getClefOffset(a);notationModel.getRangeIndex();switch(b){case cfg.TOGGLE_ON:statusModel.clefButtons[a].removeClass("off");statusModel.clefButtons[a].addClass("on");notationModel.clefIndexProperties[a]=!0;notationController.drawClef(a);break;case cfg.TOGGLE_OFF:statusModel.clefButtons[a].removeClass("on"),statusModel.clefButtons[a].addClass("off"),notationModel.clefIndexProperties[a]=
!1,a=notationModel.practiceClefIndex(),notationController.drawClef(a)}}};
Flash.Notes.Keyboard.GameController.prototype.toggleAccidental=function(a){if(!statusModel.getStart()){var a=statusModel.toggleAccidental(a),b=notationModel.getKeySignature();notationModel.getAccidentalRange();addAccidental=cfg.ACCIDENTAL_ON.single_acc||cfg.ACCIDENTAL_ON.double_acc?!0:!1;notationModel.setAddAccidental(addAccidental);switch(a){case cfg.ACC_SINGLE:$("#acc_single_sel_button").removeClass("off");$("#acc_single_sel_button").addClass("on");$("#acc_double_sel_button").removeClass("on");
$("#acc_double_sel_button").addClass("off");b===cfg.C?notationModel.setAccidentalRange(cfg.ACC_SINGLE):notationModel.setAccidentalRange(cfg.ACC_SINGLE_NOT_C);break;case cfg.ACC_DOUBLE:$("#acc_single_sel_button").removeClass("on");$("#acc_single_sel_button").addClass("off");$("#acc_double_sel_button").removeClass("off");$("#acc_double_sel_button").addClass("on");notationModel.setAccidentalRange(cfg.ACC_DOUBLE);break;case cfg.ACC_ALL:$("#acc_single_sel_button").removeClass("off");$("#acc_single_sel_button").addClass("on");
$("#acc_double_sel_button").removeClass("off");$("#acc_double_sel_button").addClass("on");b===cfg.C?notationModel.setAccidentalRange(cfg.ACC_ALL):notationModel.setAccidentalRange(cfg.ACC_ALL_NOT_C);break;case cfg.ACC_NONE:$("#acc_single_sel_button").removeClass("on"),$("#acc_single_sel_button").addClass("off"),$("#acc_double_sel_button").removeClass("on"),$("#acc_double_sel_button").addClass("off"),notationModel.setAccidentalRange(cfg.ACC_NONE)}}};
Flash.Notes.Keyboard.GameController.prototype.toggleKeyOverlay=function(){statusModel.setOverlayVisible(!statusModel.getOverlayVisible());statusView.displayKeyOverlay(statusModel.getOverlayVisible())};
Flash.Notes.Keyboard.GameController.prototype.updateKeySignature=function(a){statusModel.getStart()||(notationModel.updateKeySignature(a),a=notationModel.getKeySigIndex(),notationController.drawKeySignature(a),a!=cfg.C?(notationModel.setAddKeySignature(!0),cfg.ACCIDENTAL_ON.single_acc&&!cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_SINGLE_NOT_C),cfg.ACCIDENTAL_ON.single_acc&&cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_ALL_NOT_C)):(notationModel.setAddKeySignature(!1),
cfg.ACCIDENTAL_ON.single_acc&&!cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_SINGLE),cfg.ACCIDENTAL_ON.single_acc&&cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_ALL)),!cfg.ACCIDENTAL_ON.single_acc&&cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_DOUBLE),!cfg.ACCIDENTAL_ON.single_acc&&!cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_NONE),notationModel.convertNoteValue())};
Flash.Notes.Keyboard.GameController.prototype.setPracticeRange=function(){var a=statusModel.getPercent(),b=statusModel.getAttempts(),c=notationModel.getRangeIndex();a>=cfg.P_HIGH_PCT&&b%cfg.PRACTICE_ATT===0&&c<cfg.MAX_RANGE&&notationController.setRangeIndex(c+1);a<cfg.P_LOW_PCT&&c>cfg.MIN_RANGE&&notationController.setRangeIndex(c-1)};
Flash.Notes.Keyboard.GameController.prototype.updateLevel=function(){var a=statusModel.getLevel(),b=a%2===0?a/2-1:Math.floor(a/2),c;statusModel.setGameClefTypes();c=statusModel.getRandomClefIndex();b%=cfg.MAX_RANGE+1;if(a===cfg.MAX_LEVEL)this.setMaxLevel(!0),notationModel.setKeySignature(notationModel.randomKeySignature()),notationController.drawClef(notationController.getRandomClefIndex(4,0)),notationController.setRangeIndex(cfg.MAX_RANGE);else{switch(c){case cfg.RANDOM_TB:notationController.drawClef(notationController.getRandomClefIndex(2,
0));break;case cfg.RANDOM_AT:notationController.drawClef(notationController.getRandomClefIndex(2,2));break;default:notationController.drawClef(c)}notationController.setRangeIndex(b)}statusModel.isAccidentalLevel()?notationModel.setAddAccidental(!0):notationModel.setAddAccidental(!1);statusModel.isKeySignatureLevel()?(notationModel.setAddKeySignature(!0),notationModel.setKeySignatureLevel(statusModel.getKeySignatureLevel()),notationModel.setKeySignature(notationModel.randomKeySignature())):(notationModel.setAddKeySignature(!1),
notationModel.setKeySignature(cfg.C));statusModel.getTimeout()&&this.resetGame();this.displayScore();this.displaySessionAlert(!0,!1,!1)};Flash.Notes.Keyboard.GameController.prototype.displayPractice=function(){this.init();this.setMode(cfg.PRACTICE_MODE);$("#menu_frame").hide();$("#status_level_label").html("");$("#status_level").html("");$("#game_frame").show();$("#menu_buttons").show();$("#game_status_box").hide();$("#stop_button").hide();$("#start_button").show();statusView.initHitDisplay("hit_light")};
Flash.Notes.Keyboard.GameController.prototype.displayGame=function(){this.init();this.setMode(cfg.GAME_MODE);statusView.initLivesDisplay("game_lives",cfg.MAX_LIVES);statusView.initHitDisplay("hit_light");$("#status_level_label").html("Level:");$("#status_level").html("1");this.displaySessionAlert(!0,!1,!1)};
Flash.Notes.Keyboard.GameController.prototype.displayScore=function(){statusView.displayPoints("#status_points",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#status_percent",statusModel.getPoints(),statusModel.getAttempts());statusView.displayScore("#status_score",statusModel.getScore());statusModel.getMode()===cfg.GAME_MODE&&statusView.displayLevel("#status_level",statusModel.getLevel());statusView.displayHiScore("#hi_score",statusModel.getHiScore())};
Flash.Notes.Keyboard.GameController.prototype.displaySummary=function(){var a;$("#game_frame").hide();statusView.displayPoints("#point_summary",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#percent_summary",statusModel.getPoints(),statusModel.getAttempts());statusModel.getMode()===cfg.PRACTICE_MODE&&($("#score_summary_row").hide(),$("#level_summary_row").hide(),$("#lives_summary_row").hide(),$("#next_level_row").hide(),$("#time_summary_row").show(),a=statusModel.getTime()?
statusModel.getTime():0,$("#time_summary").html(""+a+" sec"));statusModel.getMode()===cfg.GAME_MODE&&(statusView.displayScore("#score_summary",statusModel.getScore()),$("#time_summary_row").hide(),$("#score_summary_row").show(),$("#level_summary_row").show(),$("#lives_summary_row").show(),$("#next_level_row").show(),$("#level_summary").html(""+statusModel.getLevel()),$("#lives_summary").html(""+statusModel.getLives()));$("#summary_frame").show()};
Flash.Notes.Keyboard.GameController.prototype.removeLivesDisplay=function(){statusModel.getMode()===cfg.GAME_MODE&&statusView.removeLivesDisplay()};
Flash.Notes.Keyboard.GameController.prototype.displaySessionAlert=function(a,b,c){$("#menu_frame").hide();$("#instructions_frame").hide();$("#summary_frame").hide();$("#game_frame").hide();$("#menu_buttons").hide();$("#session_frame").show();$("#game_status_box").show();a&&!b?($("#session_start_header").html("Level "+statusModel.getLevel()),$("#session_end").hide(),$("#game_end").hide(),$("#session_start").show(),$("#session_start_button").focus()):b?($("#session_start").hide(),$("#session_end").hide(),
$("#game_end").show(),$("#scores_button").focus()):($("#session_start").hide(),$("#game_end").hide(),lives=statusModel.getLives(),lives_str=lives>1?" lives":" life",$("#lives").html(""+statusModel.getLives()+lives_str+" left"),c?$("#bonus").html("BONUS PTS<br/>"+statusModel.getBonus()):$("#bonus").html("BONUS PTS<br/>0"),$("#session_end").show(),$("#session_end_button").focus())};
Flash.Notes.Keyboard.GameController.prototype.processFinalScore=function(){var a,b;a=statusModel.getScore();var c,d;statusModel.setDate();b=statusModel.getDateTime();c=statusModel.getDateString();d=statusModel.getTimeString();b="score="+a+"&time="+b+"&date_string="+c+"&time_string="+d;Modernizr.localstorage&&(c=statusModel.getHiScore(),a=c>a?c:a);statusModel.setHiScore(a);$("#score_text").html("Please wait . . . retrieving scores");ajaxUtilities.createXHR();a=ajaxUtilities.getXHR();ajaxUtilities.open("POST",
"php/get_scores.php");a.onreadystatechange=ajaxUtilities.onChange;ajaxUtilities.send("POST",b)};
Flash.Notes.Keyboard.GameController.prototype.displayFinalScore=function(a){var b,c,d,f="",e="",g="",h="your score: "+statusModel.getScore(),i=statusModel.top_scores.length;if(a)for(a=0;a<i;a++)b=parseInt(statusModel.top_scores[a]),c=statusModel.top_date_strings[a],d=parseInt(statusModel.top_times[a]),b===statusModel.getScore()&&d===statusModel.getDateTime()?(f+='<span class="your_scores">'+(a+1)+".</span><br />",e+='<span class="your_scores">'+b+"*</span><br />",g+='<span class="your_scores">'+c+
"</span><br />",h="* your score"):(f+=a+1+".<br />",e+=b+"<br />",g+=c+"<br />");else for(a=0;a<10;a++)f+=a+1+".<br />",e+="unavailable<br />",g+="unavailable<br />";$("#score_display_frame").show();$("#main_menu_button").focus();$("#top_rank").html(f);$("#top_scores").html(e);$("#top_dates").html(g);$("#top_score_footer").html(h)};$(document).ready(function(){var a="a,w,s,e,d,f,t,g,y,h,u,j,k".split(","),b="#c,#cs,#d,#ds,#e,#f,#fs,#g,#gs,#a,#as,#b,#c2".split(",");Modernizr.canvas?(cfg=new Flash.Notes.Keyboard.Config,statusModel=new Flash.Notes.Keyboard.StatusModel,statusView=new Flash.Notes.Keyboard.StatusView,notationModel=new Flash.Notes.Keyboard.NotationModel,notationController=new Flash.Notes.Keyboard.NotationController(cfg.MIN_RANGE),gameController=new Flash.Notes.Keyboard.GameController,$("div.staff_area canvas")[0].width=
cfg.BG_LAYER_WIDTH,$("div.staff_area canvas")[0].height=cfg.BG_LAYER_HEIGHT,$("div.staff_area canvas")[1].width=cfg.CLEF_LAYER_WIDTH,$("div.staff_area canvas")[1].height=cfg.BG_LAYER_HEIGHT,$("div.staff_area canvas")[2].width=cfg.KS_LAYER_WIDTH,$("div.staff_area canvas")[2].height=cfg.BG_LAYER_HEIGHT,$("div.staff_area canvas")[3].width=cfg.NOTE_LAYER_WIDTH,$("div.staff_area canvas")[3].height=cfg.BG_LAYER_HEIGHT,$(".accid_sel_Btn").addClass("off"),$("#stop").hide(),$("#menu_frame").show(),$("#practice_button").focus(),
$("#practice_button").click(function(){gameController.displayPractice()}),$("#practice_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#instructions_button").focus();a===cfg.DOWN_KEY&&$("#play_button").focus()}),$("#play_button").click(function(){gameController.displayGame()}),$("#play_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#practice_button").focus();a===cfg.DOWN_KEY&&$("#instructions_button").focus()}),$("#instructions_button").click(function(){$("#menu_frame").hide();
$("#instructions_frame").show();$("#back_button").focus()}),$("#instructions_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#play_button").focus();a===cfg.DOWN_KEY&&$("#practice_button").focus()}),$("#back_button").click(function(){$("#instructions_frame").hide();$("#menu_frame").show();$("#practice_button").focus()}),$("#start_button").click(function(){gameController.getStart()||($(this).hide(),$("#stop_button").show());gameController.startGame("#status_timer")}),$("#stop_button").click(function(){gameController.getStart()&&
($(this).hide(),$("#start_button").show());gameController.stopGame();$("#sum_continue_button").focus()}),$(".black_key_Btn").keydown(function(c){var d;d=parseInt(c.keyCode);d==="13"&&c.preventDefault();d>=65&&d<=89&&(c=statusModel.getKeyIndex(d),c!=-1&&(d=a[c],k_btn=b[c],$(k_btn).css("background-color","#127"),gameController.continueGame(c,d)))}),$(".black_key_Btn").keyup(function(a){var d=parseInt(a.keyCode);d==="13"&&a.preventDefault();d>=65&&d<=89&&(a=statusModel.getKeyIndex(d),a!=-1&&(k_btn=b[a],
$(k_btn).css("background-color","#000")))}),$(".white_key_Btn").keydown(function(c){var d;d=c.keyCode;d==="13"&&c.preventDefault();d>=65&&d<=89&&(c=statusModel.getKeyIndex(d),c!=-1&&(d=a[c],k_btn=b[c],$(k_btn).css("background-color","#127"),gameController.continueGame(c,d)))}),$(".white_key_Btn").keyup(function(a){var d=a.keyCode;d==="13"&&a.preventDefault();d>=65&&d<=89&&(a=statusModel.getKeyIndex(d),a!=-1&&(k_btn=b[a],$(k_btn).css("background-color","#fff")))}),$(".black_key_Btn").click(function(){var b=
$(this).attr("value");keyId=a[b];gameController.continueGame(b,keyId)}),$(".white_key_Btn").click(function(){var b=$(this).attr("value");gameController.continueGame(b,a[b])}),$(".overlay").click(function(){gameController.toggleKeyOverlay()}),$(".clefBtn").click(function(){var a=parseInt($(this).attr("value"));gameController.toggleClef(a);$("#c").focus()}),$(".accid_sel_Btn").click(function(){var a=$(this).attr("value");gameController.toggleAccidental(a);console.log("type: "+a);$("#c").focus()}),$(".keysig_sel_Btn").click(function(){var a=
$(this),a=parseInt(a.attr("value"));gameController.updateKeySignature(a);$("#c").focus()}),$("#session_start_button").click(function(){$("#session_frame").hide();statusModel.setTimeout(!1);$("#game_frame").show();gameController.startGame("#status_timer")}),$("#session_end_button").click(function(){$("#session_frame").hide();gameController.displaySummary();$("#sum_continue_button").focus()}),$("#scores_button").click(function(){$("#session_frame").hide();gameController.processFinalScore()}),$("#sum_continue_button").click(function(){$("#summary_frame").hide();
$("#session_frame").hide();!statusModel.getTimeout()&&statusModel.getMode()===statusModel.GAME_MODE&&gameController.startGame("#timer");statusModel.getTimeout()?gameController.updateLevel():$("#game_frame").show();$("#c").focus()}),$("#sum_continue_button").keydown(function(a){a=a.keyCode;if(a===cfg.UP_KEY||a===cfg.DOWN_KEY)$(this).blur(),$("#quit_button").focus()}),$("#quit_button").click(function(){$("#summary_frame").hide();statusModel.getMode()===cfg.GAME_MODE?(gameController.processFinalScore(),
gameController.removeLivesDisplay(),$("#score_display_frame").show()):($("#menu_frame").show(),$("#practice_button").focus())}),$("#quit_button").keydown(function(a){a=a.keyCode;(a===cfg.UP_KEY||a===cfg.DOWN_KEY)&&$("#sum_continue_button").focus()}),$("#main_menu_button").click(function(){$("#score_display_frame").hide();$("#main_menu_button").hide();gameController.init();$("#menu_frame").show();$("#practice_button").focus()}),$("button").hover(function(){$(this).css({opacity:1})},function(){$(this).css({opacity:0.9})}),
$(".overlay").hover(function(){$(this).css({opacity:1})},function(){$(this).css({opacity:0.7})}),$(".black_key_Btn").hover(function(){$(this).css({"background-color":"#127"});$(this).css({opacity:1})},function(){$(this).css({"background-color":"#000"});$(this).css({opacity:1})}),$(".white_key_Btn").hover(function(){$(this).css({"background-color":"#66a"});$(this).css({opacity:1})},function(){$(this).css({"background-color":"#fff"});$(this).css({opacity:1})}),$(".black_key_Btn").mousedown(function(){$(this).css({"background-color":"#2f2"});
$(this).css({opacity:1})}),$(".white_key_Btn").mousedown(function(){$(this).css({"background-color":"#2f2"});$(this).css({opacity:1})}),$(".black_key_Btn").mouseup(function(){$(this).css({"background-color":"#000"});$(this).css({opacity:1})}),$(".white_key_Btn").mouseup(function(){$(this).css({"background-color":"#fff"});$(this).css({opacity:1})}),$(".keysig_sel_Btn").hover(function(){$(this).css({opacity:1})},function(){$(this).css({opacity:0.95})})):$("#nocanvas_frame").show()});Flash.Notes.Keyboard.NotationController=function(a){this.setRangeIndex(a)};Flash.Notes.Keyboard.NotationController.prototype.drawStaff=function(){var a=$("div.staff_area canvas")[0],a=(new Vex.Flow.Renderer(a,Vex.Flow.Renderer.Backends.CANVAS)).getContext();(new Vex.Flow.Stave(cfg.BG_STAVE_LEFT,cfg.BG_STAVE_TOP,cfg.BG_STAVE_WIDTH,Vex.Flow.stave_specs[cfg.LARGE])).setContext(a).draw(a,!1,!1)};
Flash.Notes.Keyboard.NotationController.prototype.drawClef=function(a){var b=$("div.staff_area canvas")[1],b=(new Vex.Flow.Renderer(b,Vex.Flow.Renderer.Backends.CANVAS)).getContext(),c=new Vex.Flow.Stave(cfg.CLEF_LAYER_LEFT+10,cfg.FG_STAVE_TOP,cfg.CLEF_LAYER_WIDTH,Vex.Flow.stave_specs[cfg.LARGE]),d=cfg.CLEF_TYPES[a],f=notationModel.getKeySigIndex();notationModel.setClefIndex(a);b.clearRect(0,0,cfg.CLEF_LAYER_WIDTH,cfg.BG_LAYER_HEIGHT);c.addClef(d).setContext(b).draw(b,!1,!1);this.drawKeySignature(f);
notationModel.convertNoteValue()};
Flash.Notes.Keyboard.NotationController.prototype.drawNote=function(){var a=$("div.staff_area canvas")[3],b=notationModel.getClefIndex(),c=cfg.CLEF_TYPES[b],d,a=(new Vex.Flow.Renderer(a,Vex.Flow.Renderer.Backends.CANVAS)).getContext(),f=new Vex.Flow.Stave(cfg.NOTE_LAYER_LEFT,cfg.FG_STAVE_TOP,cfg.NOTE_LAYER_WIDTH-10,Vex.Flow.stave_specs[cfg.LARGE]),e=notationModel.getRangeIndex(),g=Flash.Notes.Keyboard.noteRangeProperties(b),h=g.upper_octave[e]-g.base_octave[e]+1,i=Math.round(Math.random()*10)%h,b=
g.base_octave[e]+i;a.clearRect(0,0,cfg.NOTE_LAYER_WIDTH,cfg.BG_LAYER_HEIGHT);notationModel.setOctave(b);i===0?(h=g.base_index[e],e=6-h):i===h-1?(h=0,e=g.upper_index[e]):(h=0,e=6);e=e>0?Math.round(Math.random()*1E4)%e:0;e=h+e;notationModel.setNoteIndex(e);e=Vex.Flow.integerToNoteLetter(e);notationModel.getAddAccidental()&&(d=notationModel.randomAccidental())&&(e+=d);notationModel.getAddKeySignature()&&!d&&(e+=Flash.Notes.Keyboard.keySignatureAccidentals(notationModel.getKeySignature(),notationModel.getNoteIndex()),
this.drawKeySignature(notationModel.getKeySigIndex()));e=""+e+"/"+b+"";notationModel.setNoteValue(e);c=(new Vex.Flow.StaveNote({keys:[e],duration:"w",clef:c,size:cfg.LARGE_W})).setRenderOptions();d&&c.addAccidental(0,new Vex.Flow.Accidental(d));f.setContext(a).draw(a,!1,!1);Vex.Flow.Formatter.FormatAndDraw(a,f,[c],Vex.Flow.TIME4_4)};
Flash.Notes.Keyboard.NotationController.prototype.hideNote=function(){var a=$("div.staff_area canvas")[3],a=(new Vex.Flow.Renderer(a,Vex.Flow.Renderer.Backends.CANVAS)).getContext();a.clearRect(0,0,cfg.NOTE_LAYER_WIDTH,cfg.BG_LAYER_HEIGHT);(new Vex.Flow.Stave(cfg.NOTE_LAYER_LEFT,cfg.FG_STAVE_TOP,cfg.NOTE_LAYER_WIDTH-10,Vex.Flow.stave_specs[cfg.LARGE])).setContext(a).draw(a,!1,!1)};
Flash.Notes.Keyboard.NotationController.prototype.drawKeySignature=function(a){var b=notationModel.getClefIndex(),c=$("div.staff_area canvas")[2],c=(new Vex.Flow.Renderer(c,Vex.Flow.Renderer.Backends.CANVAS)).getContext(),d=notationModel.getKeySignature(a),f=new Vex.Flow.Stave(cfg.KS_LAYER_LEFT,cfg.FG_STAVE_TOP,cfg.KS_LAYER_WIDTH,Vex.Flow.stave_specs[cfg.LARGE]);c.clearRect(0,0,cfg.KS_LAYER_WIDTH,cfg.BG_LAYER_HEIGHT);f.addKeySignature(d,b).setContext(c).draw(c,!1,!1);notationModel.setKeySignature(a)};
Flash.Notes.Keyboard.NotationController.prototype.drawTimeSignature=function(){};Flash.Notes.Keyboard.NotationController.prototype.getNoteValue=function(){return notationModel.getNoteValue()};Flash.Notes.Keyboard.NotationController.prototype.setRangeIndex=function(a){notationModel.setRangeIndex(a)};Flash.Notes.Keyboard.NotationController.prototype.getRandomClefIndex=function(a,b){return notationModel.randomClefIndex(a,b)};Flash.Notes.Keyboard.NotationController.prototype.getRandomKeySignature=function(){return notationModel.randomKeySignature()};Flash.Notes.Keyboard.NotationModel=function(){this.ledgerLines=this.valOffset=this.notePos=0;this.range=cfg.MIN_RANGE;this.noteIndex=this.clefIndex=this.prevClefIndex=0;this.key_signature_level=this.noteValue=this.octave=-1;this.ks_index=this.keySig=cfg.C;this.KS_MIN=cfg.CF;this.KS_MAX=cfg.CS;this.accidental_range=cfg.SINGLE_C;this.add_accidental=!1;this.accidental_type=cfg.ACC_TYPE_C;this.add_key_signature=!1;this.clefIndexArray=[cfg.TREBLE,cfg.BASS,cfg.ALTO,cfg.TENOR];this.clefIndexProperties={0:!0,
1:!1,2:!1,3:!1};this.keysig_acc_type={sharp:"#",flat:"b"}};Flash.Notes.Keyboard.NotationModel.prototype.setNoteIndex=function(a){this.noteIndex=a;if(this.index<0)this.noteIndex=0;if(this.index>6)this.noteIndex=6;return this};Flash.Notes.Keyboard.NotationModel.prototype.getNoteIndex=function(){return this.noteIndex};Flash.Notes.Keyboard.NotationModel.prototype.setOctave=function(a){this.octave=a;return this};Flash.Notes.Keyboard.NotationModel.prototype.getOctave=function(){return this.octave};
Flash.Notes.Keyboard.NotationModel.prototype.convertNoteIndex=function(){var a=this.getNoteIndex(),b=[0,2,1,6];this.setNoteIndex(Math.abs((a-(b[this.prevClefIndex]-b[this.clefIndex]))%7));return this};Flash.Notes.Keyboard.NotationModel.prototype.convertNoteValue=function(){notationModel.getClefIndex();var a=this.getNoteIndex(),b=Vex.Flow.integerToNoteLetter(a),c=this.checkOctaveRange();b+=Flash.Notes.Keyboard.keySignatureAccidentals(this.getKeySignature(),a);this.setNoteValue(""+b+"/"+c)};
Flash.Notes.Keyboard.NotationModel.prototype.checkOctaveRange=function(){var a=this.getOctave(),b=notationModel.getClefIndex(),c=this.getRangeIndex(),d=this.getNoteIndex(),f=Flash.Notes.Keyboard.noteRangeProperties(b),b=f.base_octave[c],e=f.upper_octave[c],g=f.base_index[c],c=f.upper_index[c];a<b&&(a=b);a===b&&d<g&&(a=b+1);a>e&&(a=e);a===e&&d>c&&(a=e-1);return a};Flash.Notes.Keyboard.NotationModel.prototype.setClefIndex=function(a){this.prevClefIndex=this.getClefIndex();this.clefIndex=a;return this};
Flash.Notes.Keyboard.NotationModel.prototype.getClefIndex=function(){return this.clefIndex};Flash.Notes.Keyboard.NotationModel.prototype.setNoteValue=function(a){var b;b=Vex.Flow.keyProperties(a,cfg.CLEF_TYPES[this.clefIndex]);a=b.int_value%12;this.noteValue=a};Flash.Notes.Keyboard.NotationModel.prototype.getNoteValue=function(){return this.noteValue};Flash.Notes.Keyboard.NotationModel.prototype.setAddAccidental=function(a){this.add_accidental=a;return this};
Flash.Notes.Keyboard.NotationModel.prototype.getAddAccidental=function(){return this.add_accidental};Flash.Notes.Keyboard.NotationModel.prototype.setAccidentalType=function(a){this.accidental_type=a;return this};Flash.Notes.Keyboard.NotationModel.prototype.getAccidentalType=function(){return this.accidental_type};Flash.Notes.Keyboard.NotationModel.prototype.setAddKeySignature=function(a){this.add_key_signature=a;return this};Flash.Notes.Keyboard.NotationModel.prototype.getAddKeySignature=function(){return this.add_key_signature};
Flash.Notes.Keyboard.NotationModel.prototype.setKeySignatureLevel=function(a){this.key_signature_level=a;return this};Flash.Notes.Keyboard.NotationModel.prototype.getKeySignatureLevel=function(){return this.key_signature_level};Flash.Notes.Keyboard.NotationModel.prototype.getKeySignature=function(){return cfg.KEY_SIGS[this.keySig]};Flash.Notes.Keyboard.NotationModel.prototype.getKeySigIndex=function(){return this.keySig};
Flash.Notes.Keyboard.NotationModel.prototype.setKeySignature=function(a){this.keySig=a;return this};Flash.Notes.Keyboard.NotationModel.prototype.updateKeySignature=function(a){var b=this.keySig+a;this.keySig=a<0?b>=this.KS_MIN?b:this.KS_MIN:b<=this.KS_MAX?b:this.KS_MAX;this.convertNoteValue()};Flash.Notes.Keyboard.NotationModel.prototype.setKsIndex=function(a){this.ks_index=a;return this};
Flash.Notes.Keyboard.NotationModel.prototype.setRangeIndex=function(a){if(a<cfg.MIN_RANGE)this.range=cfg.MIN_RANGE;this.range=a>cfg.MAX_RANGE?cfg.MAX_RANGE:a;return this};Flash.Notes.Keyboard.NotationModel.prototype.getRangeIndex=function(){return this.range};Flash.Notes.Keyboard.NotationModel.prototype.randomClefIndex=function(a,b){return this.clefIndexArray[Math.round(Math.random()*100)%a+b]};
Flash.Notes.Keyboard.NotationModel.prototype.practiceClefIndex=function(){var a,b;for(a=0;a<4;a++)if(b=this.clefIndexProperties[a])return this.clefIndexArray[a];return null};Flash.Notes.Keyboard.NotationModel.prototype.setAccidentalRange=function(a){this.accidental_range=a;return this};Flash.Notes.Keyboard.NotationModel.prototype.getAccidentalRange=function(){return this.accidental_range};
Flash.Notes.Keyboard.NotationModel.prototype.randomAccidental=function(){var a=this.getAccidentalRange(),b=null,c=[null,"b","#","bb","##","n"],d=[null,"b","#","n"],f=[null,"bb","##"],e=c.length,g=d.length,h=f.length;this.getNoteIndex();this.getKeySignature();switch(a){case cfg.ACC_ALL:a=Math.round(Math.random()*1E3)%(e-1);b=c[a];break;case cfg.ACC_ALL_NOT_C:a=Math.round(Math.random()*1E3)%e;(b=c[a])&&(b=this.filterAccidental(b));break;case cfg.ACC_SINGLE:a=Math.round(Math.random()*1E3)%(g-1);b=d[a];
break;case cfg.ACC_SINGLE_NOT_C:a=Math.round(Math.random()*1E3)%g;(b=d[a])&&(b=this.filterAccidental(b));break;case cfg.ACC_DOUBLE:a=Math.round(Math.random()*1E3)%h,b=f[a]}return b};Flash.Notes.Keyboard.NotationModel.prototype.filterAccidental=function(a){var b=this.getKeySignature(),c=this.getNoteIndex(),b=Flash.Notes.Keyboard.keySignatureAccidentals(b,c);return a==="##"||a==="bb"?a:a==="n"?b!=""?a:null:b==""?a:null};
Flash.Notes.Keyboard.NotationModel.prototype.randomKeySignature=function(){var a;this.getKeySignatureLevel()===cfg.EASY_KEYS?(a=cfg.KS_EASY.length,a=Math.round(Math.random()*1E3)%a,a=cfg.KS_EASY[a]):(a=cfg.KS_HARD.length,a=Math.round(Math.random()*1E3)%a,a=cfg.KS_HARD[a]);return a};
Flash.Notes.Keyboard.NotationModel.prototype.getImgUrl=function(a){switch(a){case cfg.TREBLE:return"images/treble.png";case cfg.BASS:return"images/bass.png";case cfg.ALTO:return"images/c_clef.png";case cfg.TENOR:return"images/c_clef.png";default:return"images/treble.png"}};
Flash.Notes.Keyboard.NotationModel.prototype.getClefOffset=function(a){switch(a){case cfg.TREBLE:return cfg.TREBLE_OFFSET;case cfg.BASS:return cfg.BASS_OFFSET;case cfg.ALTO:return cfg.ALTO_OFFSET;case cfg.TENOR:return cfg.TENOR_OFFSET;default:return cfg.TREBLE_OFFSET}};Flash.Notes.Keyboard.NotationView=function(a,b,c){this.PROPS={numLines:5,space:14,ledgerLines:1,numPos:15};this.box=new Box(a,b,c);this.paper=this.box.ctx();this.RECT_X=42;this.RECT_Y=0;this.RECT_W=b-42;this.RECT_H=(6+2*this.PROPS.ledgerLines+this.PROPS.numLines+1)*this.PROPS.space;this.STAFF_X=this.RECT_X+10;this.STAFF_Y=this.RECT_Y+(4+this.PROPS.ledgerLines)*this.PROPS.space;this.STAFF_W=this.RECT_W-20;this.staff=new Staff(this.STAFF_X,this.STAFF_Y,this.STAFF_W,this.PROPS);this.valueOffset=this.clefType=
this.notePos=-1};Flash.Notes.Keyboard.NotationView.prototype.staffPath=function(){return this.staff.path()};Flash.Notes.Keyboard.NotationView.prototype.clef=function(a,b){return new Clef(this.STAFF_X,this.STAFF_Y,this.PROPS.space,a,b)};Flash.Notes.Keyboard.NotationView.prototype.note=function(a,b){var c=new Note(this.STAFF_X+this.STAFF_W/2,b.bottomPos(),a,this.PROPS.space,"images/whole.png");this.pos=a;return c};Flash.Notes.Keyboard.NotationView.prototype.keySignature=function(){};
Flash.Notes.Keyboard.NotationView.prototype.accidental=function(){};Flash.Notes.Keyboard.NotationView.prototype.ledgerLinePath=function(a,b){var c=0,d=Math.abs(a),f="";a>0&&(c=1);a<0&&(c=-1);switch(c){case 1:f+=b.ledgerPath(this.STAFF_Y+5*this.PROPS.space,d,c);break;case -1:f+=b.ledgerPath(this.STAFF_Y-this.PROPS.space,d,c)}return f};Flash.Notes.Keyboard.StatusModel=function(){var a,b,c,d,f=0,e=0,g=0,h=0,i=0,j=5,l=!1,m=cfg.TIMEOUT,n=!1,o=!1,p,k;k=Modernizr.localstorage?(p=parseInt(localStorage.getItem("hiscore_keys")))?p:0:0;this.getTime=function(){return a};this.setTime=function(b){a=b};this.getMode=function(){return b};this.setMode=function(a){b=a};this.setDate=function(){c=new Date;d=c.getTime()};this.getDateTime=function(){return d};this.getDateString=function(){var a=""+(c.getMonth()+1),b=c.getDate()<10?"0"+c.getDate():c.getDate();
return a+"-"+b+"-"+c.getFullYear()};this.getTimeString=function(){var a=""+c.getHours(),b=c.getMinutes()<10?"0"+c.getMinutes():c.getMinutes(),d=c.getSeconds()<10?"0"+c.getSeconds():c.getSeconds();return a+":"+b+":"+d};this.addPoint=function(){f+=1};this.setPoints=function(a){f=a};this.getPoints=function(){return f};this.addAttempt=function(){e+=1};this.setAttempts=function(a){e=a};this.getAttempts=function(){return e};this.getPercent=function(){return Math.floor(f/e*100)};this.calculateScore=function(){g+=
f*h};this.addBonus=function(){i=cfg.BONUS*h;g+=i};this.getBonus=function(){return i};this.setScore=function(a){g=a};this.getScore=function(){return g};this.getHiScore=function(){return k};this.setHiScore=function(a){k=a;Modernizr.localstorage&&localStorage.setItem("hiscore_keys",k)};this.setLevel=function(a){h=a;h>cfg.BONUS_LEVEL&&(cfg.BONUS+=cfg.BONUS_INC)};this.getLevel=function(){return h};this.advanceLevel=function(){this.setLevel(h<cfg.MAX_LEVEL?h+=1:cfg.MAX_LEVEL);return this};this.decLives=
function(){j-=1;j<0&&(j=0)};this.setLives=function(a){j=a};this.getLives=function(){return j};this.start=function(a){l=a};this.getStart=function(){return l};this.setTimeInterval=function(a){m=a};this.getTimeInterval=function(){return m};this.setTimeout=function(a){n=a};this.getTimeout=function(){return n};this.getOverlayVisible=function(){return o};this.setOverlayVisible=function(a){o=a};this.top_scores=[];this.top_times=[];this.top_date_strings=[];this.top_time_strings=[];this.active_clefs=[!0,!1,
!1,!1];this.clefIndexArray=[cfg.TREBLE,cfg.BASS,cfg.ALTO,cfg.TENOR];this.clefButtons=[$("#treble_button"),$("#bass_button"),$("#alto_button"),$("#tenor_button")]};Flash.Notes.Keyboard.StatusModel.prototype.isAccidentalLevel=function(){var a,b=cfg.ACC_LEVELS,c=b.length;for(a=0;a<c;a++)if(this.getLevel()===b[a])return!0;return!1};
Flash.Notes.Keyboard.StatusModel.prototype.isKeySignatureLevel=function(){return this.getLevel()>=cfg.KS_TIER_1[0]&&this.getLevel()<=cfg.KS_TIER_1[1]?!0:this.getLevel()>=cfg.KS_TIER_2[0]&&this.getLevel()<=cfg.KS_TIER_2[1]?!0:!1};Flash.Notes.Keyboard.StatusModel.prototype.getKeySignatureLevel=function(){var a,b=cfg.KS_EASY_LEVELS,c=cfg.KS_HARD_LEVELS,d=b.length,f=c.length;for(a=0;a<d;a++)if(this.getLevel()===b[a])return cfg.EASY_KEYS;for(a=0;a<f;a++)if(this.getLevel()===c[a])return cfg.HARD_KEYS;return null};
Flash.Notes.Keyboard.StatusModel.prototype.isLevelAdvance=function(){return this.getPercent()>=cfg.MIN_PERCENT&&this.getTimeout()&&this.getAttempts()>=cfg.MIN_ATTEMPTS?!0:!1};Flash.Notes.Keyboard.StatusModel.prototype.setGameClefTypes=function(){var a,b=this.getLevel();b<=cfg.TIER_1&&(a=b%2===0,a=[!a,a,!1,!1]);b>cfg.TIER_1&&b<=cfg.TIER_2&&(a=[!0,!0,!1,!1]);b>cfg.TIER_2&&b<=cfg.TIER_3&&(a=b%2===0,a=[!1,!1,!a,a]);b>cfg.TIER_3&&b<=cfg.TIER_4&&(a=[!1,!1,!0,!0]);b>cfg.TIER_4&&(a=[!0,!0,!0,!0]);this.set_clef(a)};
Flash.Notes.Keyboard.StatusModel.prototype.set_clef=function(a){var b;for(b=0;b<4;b++)this.active_clefs[b]=a[b]};Flash.Notes.Keyboard.StatusModel.prototype.getRandomClefIndex=function(){var a,b=[],c=0;for(a=0;a<4;a++)this.active_clefs[a]===!0&&(b[c]=a,c+=1);b.length===1?a=b[0]:(a=Math.round(Math.random()*100)%b.length,a=b[a]);return this.clefIndexArray[a]};
Flash.Notes.Keyboard.StatusModel.prototype.toggleClefButton=function(a){var b,c=0;if(this.active_clefs[a]){for(b=0;b<4;b++)c+=this.active_clefs[b]===!0?1:0;if(c===1)return cfg.TOGGLE_NONE}this.active_clefs[a]=!this.active_clefs[a];return this.active_clefs[a]?cfg.TOGGLE_ON:cfg.TOGGLE_OFF};
Flash.Notes.Keyboard.StatusModel.prototype.toggleAccidental=function(a){var b=cfg.ACCIDENTAL_ON,c;b[a]=!b[a];a=cfg.ACCIDENTAL_ON.single_acc;b=cfg.ACCIDENTAL_ON.double_acc;console.log("acc_single: "+a+" acc_double: "+b);if(a&&!b)c=cfg.ACC_SINGLE;if(!a&&b)c=cfg.ACC_DOUBLE;if(a&&b)c=cfg.ACC_ALL;if(!a&&!b)c=cfg.ACC_NONE;return c};
Flash.Notes.Keyboard.StatusModel.prototype.getKeyIndex=function(a){switch(a){case cfg.KEY_C:return 0;case cfg.KEY_CS:return 1;case cfg.KEY_D:return 2;case cfg.KEY_DS:return 3;case cfg.KEY_E:return 4;case cfg.KEY_F:return 5;case cfg.KEY_FS:return 6;case cfg.KEY_G:return 7;case cfg.KEY_GS:return 8;case cfg.KEY_A:return 9;case cfg.KEY_AS:return 10;case cfg.KEY_B:return 11;case cfg.KEY_C2:return 12;default:return-1}};Flash.Notes.Keyboard.StatusView=function(){var a,b,c,d,f,e,g,h=[],i,j;this.initLivesDisplay=function(c,d){b=Raphael(c,60,20);for(a=0;a<d;a++)h[a]=b.circle(10*(a+1),5,4.5).attr({fill:"green",stroke:"#000"})};this.updateLivesDisplay=function(){i=h.length;i>0&&(h[i-1].remove(),h.pop())};this.removeLivesDisplay=function(){b.remove()};this.drawStatusBar=function(a,b,e,f){c=Raphael(a,b,e,f);d=c.rect(0,0,e,f);d.attr({stroke:"red",fill:"#202000"})};this.initHitDisplay=function(a){f=Raphael(a,0,0);e=f.path("M 5 18 L 17 30 L 33 2 L 17 23 Z").attr({stroke:"#447",
"stroke-width":1});g=f.path("M 5 5 L 35 35 M 35 5 L 5 35").attr({stroke:"#447","stroke-width":5});e.hide();g.hide()};this.removeHitDisplay=function(){f.remove();$(".hit_box").hide()};this.updateHitDisplay=function(a){a?(e.attr({stroke:"#0c2",fill:"#0c2"}),g.hide(),e.show()):(g.attr({stroke:"#f00"}),e.hide(),g.show());this.startHitTimer();$(".hit_box").show()};this.startHitTimer=function(){var a=this;j=setTimeout(function(){a.stopHitTimer()},600)};this.stopHitTimer=function(){e.hide();g.hide();$(".hit_box").hide();
clearTimeout(j)}};Flash.Notes.Keyboard.StatusView.prototype.displayTime=function(a,b){var c="00:",d=b>=0?""+b:""+(b+1);b<10&&(c="00:0");$(a).html(c+d)};Flash.Notes.Keyboard.StatusView.prototype.displayLevel=function(a,b){var c;$(a).html(""+b)};Flash.Notes.Keyboard.StatusView.prototype.displayPoints=function(a,b,c){$(a).html(""+b+"/"+c)};Flash.Notes.Keyboard.StatusView.prototype.displayPercent=function(a,b,c){b=""+(c>0?Math.round(b/c*100):0)+"%";$(a).html(b)};
Flash.Notes.Keyboard.StatusView.prototype.displayScore=function(a,b){var c;$(a).html(""+b)};Flash.Notes.Keyboard.StatusView.prototype.displayHiScore=function(a,b){var c;$(a).html(""+b)};
Flash.Notes.Keyboard.StatusView.prototype.displayKeyOverlay=function(a){var b=document.getElementById("black_keys"),c=document.getElementById("white_keys").getElementsByTagName("button"),b=b.getElementsByTagName("button"),d="c_,d_,e_,f_,g_,a_,b_,c2_".split(","),f=["cs_","ds_","fs_","gs_","as_"],e,g;if(a){for(a=0;a<c.length;a++)e=d[a]+"overlay",g="#white_keys button:nth-child("+(a+1)+")",$(g).addClass(e);for(a=0;a<b.length;a++)e=f[a]+"overlay",g="#black_keys button:nth-child("+(a+1)+")",$(g).addClass(e)}else{for(a=
0;a<c.length;a++)e=d[a]+"overlay",g="#white_keys button:nth-child("+(a+1)+")",$(g).removeClass(e);for(a=0;a<b.length;a++)e=f[a]+"overlay",g="#black_keys button:nth-child("+(a+1)+")",$(g).removeClass(e)}};
